--First we must create the database for the project.
CREATE DATABASE IF NOT EXISTS Weigand_Portfolio;
USE Weigand_Portfolio;
CREATE TABLE IF NOT EXISTS STATE_ABBREVIATIONS (
    STATE_ABBR VARCHAR(2) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    PRIMARY KEY (STATE_ABBR)
);
-- Insert the state abbreviations into the STATE_ABBREVIATIONS table.
USE WEIGAND_PORTFOLIO;
INSERT INTO STATE_ABBREVIATIONS (STATE_ABBR, STATE)
VALUES ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('DC', 'District of Columbia'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
    ('PR', 'Puerto Rico'),
    ('GU', 'Guam'),
    ('VI', 'U.S. Virgin Islands'),
    ('AS', 'American Samoa'),
    ('MP', 'Northern Mariana Islands');
-- Adding Type to deliniate states and territories
ALTER TABLE STATE_ABBREVIATIONS
ADD TYPE CHAR(1) NOT NULL DEFAULT 'S';
-- Update TYPE: 'O' for territories and DC
UPDATE STATE_ABBREVIATIONS
SET TYPE = 'O'
WHERE STATE_ABBR IN ('DC', 'PR', 'GU', 'VI', 'AS', 'MP');
-- VERIFY THE DATA
USE WEIGAND_PORTFOLIO;
SELECT *
FROM STATE_ABBREVIATIONS;
SELECT TYPE,
    COUNT(STATE)
FROM STATE_ABBREVIATIONS
GROUP BY TYPE;
SELECT *
FROM STATE_ABBREVIATIONS
WHERE TYPE = "O";
DESCRIBE STATE_ABBREVIATIONS;
SHOW COLUMNS
FROM STATE_ABBREVIATIONS;
SELECT *
FROM STATE_ABBREVIATIONS
WHERE TYPE = 'O';
-- create the table
USE Weigand_Portfolio;
-- DROP TABLE IF EXISTS STATE_LIFE_EXPECTANCY;
CREATE TABLE IF NOT EXISTS STATE_LIFE_EXPECTANCY (
    STATE VARCHAR(50) NOT NULL,
    LIFE_EXPECTANCY DECIMAL(4, 1) NOT NULL,
    STANDARD_ERROR DECIMAL(4, 3) NOT NULL,
    MALE_EXPECTANCY DECIMAL(4, 1) NOT NULL,
    MALE_ERROR DECIMAL(4, 3) NOT NULL,
    FEMALE_EXPECTANCY DECIMAL(4, 1) NOT NULL,
    FEMALE_ERROR DECIMAL(4, 3) NOT NULL,
    DELTA_F_M DECIMAL(4, 1) NOT NULL,
    PRIMARY KEY (STATE)
);
-- Verify the table structure
USE WEIGAND_PORTFOLIO;
DESCRIBE STATE_LIFE_EXPECTANCY;
/* Import Data into the new table.
 Run C:\Development\02. SQL Examples\Convert_Secure_CSV.py to convert excel to CSV and save in the secure file priv directory.
 Easily do this by rinning 'python convert_secure_CSV.py' in the terminal.
 SHOW VARIABLES LIKE 'SECURE_FILE_PRIV';
 Once you have the CSV saved in the secure folder just load the data into the table as shown below. 
 This process will be repeated for all data imports.
 */
USE WEIGAND_PORTFOLIO;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/Life Expectancy by State.csv' INTO TABLE STATE_LIFE_EXPECTANCY FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (
    STATE,
    LIFE_EXPECTANCY,
    STANDARD_ERROR,
    MALE_EXPECTANCY,
    MALE_ERROR,
    FEMALE_EXPECTANCY,
    FEMALE_ERROR,
    DELTA_F_M
);
-- VERIFY THE DATA matches source file
SELECT *
FROM STATE_LIFE_EXPECTANCY;
SELECT COUNT(*)
FROM STATE_LIFE_EXPECTANCY;
-- Now we need to join the STATE_LIFE_EXPECTANCY table with the STATE_ABBREVIATIONS table to add the state abbreviations.
START TRANSACTION;
-- RENAME AS TEMP TABLE
RENAME TABLE STATE_LIFE_EXPECTANCY TO STATE_LIFE_EXPECTANCY_TEMP;
-- CREATE NEW STATE_LIFE_EXPECTANCY TABLE WITH STATE ABBREVIATIONS JOINED
USE WEIGAND_PORTFOLIO;
CREATE TABLE IF NOT EXISTS STATE_LIFE_EXPECTANCY AS (
    SELECT T1.STATE,
        T2.STATE_ABBR,
        T2.TYPE,
        T1.LIFE_EXPECTANCY,
        T1.STANDARD_ERROR,
        T1.MALE_EXPECTANCY,
        T1.MALE_ERROR,
        T1.FEMALE_EXPECTANCY,
        T1.FEMALE_ERROR,
        T1.DELTA_F_M
    FROM STATE_LIFE_EXPECTANCY_TEMP T1
        LEFT JOIN STATE_ABBREVIATIONS T2 ON T1.STATE = T2.STATE
);
-- DROP TEMP TABLE
DROP TABLE IF EXISTS STATE_LIFE_EXPECTANCY_TEMP;
ALTER TABLE STATE_LIFE_EXPECTANCY
ADD PRIMARY KEY (STATE_ABBR);
COMMIT;
-- VERIFY THE DATA matches source file
DESCRIBE WEIGAND_PORTFOLIO.STATE_LIFE_EXPECTANCY;
SELECT *
FROM STATE_LIFE_EXPECTANCY;
SELECT COUNT(*)
FROM STATE_LIFE_EXPECTANCY;
--------------------------------------------------------------
/* IMPORT OTHER DATASETS
 "C:\Development\02. SQL Examples\2023 ACS Health Insurance by State (Census Bureau).xlsx"
 "C:\Development\02. SQL Examples\2023 ASFIN State Totals.xlsx"
 "C:\Development\02. SQL Examples\ACSDP1Y2023.DP02-2025-06-03 (Disability).xlsx"
 "C:\Development\02. SQL Examples\ACSDP1Y2023.DP03-2025-06-03 (Economic Data).xlsx"
 REMEMBER: python convert_secure_CSV.py */
/* 
 Template Structure for importing data from CSV files into MySQL tables.
 ------------------------------------------------------------------
 USE Weigand_Portfolio;
 -- DROP TABLE IF EXISTS TABLE_NAME;
 CREATE TABLE IF NOT EXISTS TABLE_NAME (
 COLUMN1 VARCHAR(50) NOT NULL,
 COLUMN2 DECIMAL(10, 2) NOT NULL,
 COLUMN3 INT NOT NULL,
 COLUMN4 DATE NOT NULL,
 PRIMARY KEY (COLUMN1)
 );
 -- Verify the table structure
 DESCRIBE TABLE_NAME;
 
 -- Import Data into the new table.
 -- python convert_excel_to_csv.py 
 
 LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/Life Expectancy by State.csv' 
 INTO TABLE TABLE_NAME FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (
 COLUMN1,
 COLUMN2,
 COLUMN3,
 COLUMN4...
 );
 -- VERIFY THE DATA matches source file
 SELECT *
 FROM TABLE_NAME;
 SELECT COUNT(*)
 FROM TABLE_NAME;
 
 ------------------------------------------------------------------ */
USE WEIGAND_PORTFOLIO;
DROP TABLE IF EXISTS STATE_EXPENDITURE;
CREATE TABLE IF NOT EXISTS STATE_EXPENDITURE (
    STATE VARCHAR(50) NOT NULL,
    EDUCATION DECIMAL(14, 0) NOT NULL,
    PUBLIC_WELFARE DECIMAL(14, 0) NOT NULL,
    HOSPITALS DECIMAL(14, 0) NOT NULL,
    HEALTH DECIMAL(14, 0) NOT NULL,
    HIGHWAYS DECIMAL(14, 0) NOT NULL,
    POLICE_PROTECTION DECIMAL(14, 0) NOT NULL,
    CORRECTION DECIMAL(14, 0) NOT NULL,
    NATURAL_RESOURCES DECIMAL(14, 0) NOT NULL,
    PARKS_AND_RECREATION DECIMAL(14, 0) NOT NULL,
    GOVERNMENTAL_ADMINISTRATION DECIMAL(14, 0) NOT NULL,
    INTEREST_ON_GENERAL_DEBT DECIMAL(14, 0) NOT NULL,
    OTHER_AND_UNALLOCABLE DECIMAL(14, 0) NOT NULL
);
USE WEIGAND_PORTFOLIO;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/2023 ASFIN State Totals.csv' INTO TABLE STATE_EXPENDITURE FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (
    STATE,
    EDUCATION,
    PUBLIC_WELFARE,
    HOSPITALS,
    HEALTH,
    HIGHWAYS,
    POLICE_PROTECTION,
    CORRECTION,
    NATURAL_RESOURCES,
    PARKS_AND_RECREATION,
    GOVERNMENTAL_ADMINISTRATION,
    INTEREST_ON_GENERAL_DEBT,
    OTHER_AND_UNALLOCABLE
);
DESCRIBE STATE_EXPENDITURE;
SELECT *
FROM STATE_EXPENDITURE;
-- RENAME AS TEMP TABLE
RENAME TABLE STATE_EXPENDITURE TO STATE_EXPENDITURE_TEMP;
--Join Abbreviations to the STATE_EXPENDITURE table
USE WEIGAND_PORTFOLIO;
CREATE TABLE IF NOT EXISTS STATE_EXPENDITURE AS (
    SELECT T1.STATE,
        T2.STATE_ABBR,
        T2.TYPE,
        T1.EDUCATION,
        T1.PUBLIC_WELFARE,
        T1.HOSPITALS,
        T1.HEALTH,
        T1.HIGHWAYS,
        T1.POLICE_PROTECTION,
        T1.CORRECTION,
        T1.NATURAL_RESOURCES,
        T1.PARKS_AND_RECREATION,
        T1.GOVERNMENTAL_ADMINISTRATION,
        T1.INTEREST_ON_GENERAL_DEBT,
        T1.OTHER_AND_UNALLOCABLE
    FROM STATE_EXPENDITURE_TEMP T1
        LEFT JOIN STATE_ABBREVIATIONS T2 ON T1.STATE = T2.STATE
);
-- DROP TEMP TABLE
DROP TABLE IF EXISTS STATE_EXPENDITURE_TEMP;
ALTER TABLE STATE_LIFE_EXPECTANCY
ADD KEY (STATE_ABBR);
SELECT *
FROM STATE_EXPENDITURE_TEMP;
SELECT *
FROM STATE_EXPENDITURE;
-------------------
-- CREATE TABLE - INSURED BY STATE
USE WEIGAND_PORTFOLIO;
DROP TABLE IF EXISTS INSURED_BY_STATE;
CREATE TABLE IF NOT EXISTS INSURED_BY_STATE (
    STATE VARCHAR(50) NOT NULL,
    CIVI_NONINST_POP BIGINT NOT NULL,
    MALE BIGINT NOT NULL,
    FEMALE BIGINT NOT NULL,
    NATIVE_BORN BIGINT NOT NULL,
    NATURALIZED BIGINT NOT NULL,
    NOT_A_CITIZEN BIGINT NOT NULL,
    WITH_A_DISABILITY BIGINT NOT NULL,
    NO_DISABILITY BIGINT NOT NULL,
    HH_INCOME_UNDER_25K BIGINT NOT NULL,
    HH_INCOME_25_50K BIGINT NOT NULL,
    HH_INCOME_50_75K BIGINT NOT NULL,
    HH_INCOME_75_100K BIGINT NOT NULL,
    HH_INCOME_OVER_100K BIGINT NOT NULL
);
-- "C:\ProgramData\MySQL\MySQL Server 9.3\Uploads\Insured - Health Insurance by State (2023 Census).csv"
USE WEIGAND_PORTFOLIO;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/Insured - Health Insurance by State (2023 Census).csv' INTO TABLE INSURED_BY_STATE FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (
    STATE,
    CIVI_NONINST_POP,
    MALE,
    FEMALE,
    NATIVE_BORN,
    NATURALIZED,
    NOT_A_CITIZEN,
    WITH_A_DISABILITY,
    NO_DISABILITY,
    HH_INCOME_UNDER_25K,
    HH_INCOME_25_50K,
    HH_INCOME_50_75K,
    HH_INCOME_75_100K,
    HH_INCOME_OVER_100K
);
DESCRIBE INSURED_BY_STATE;
SELECT *
FROM INSURED_BY_STATE_TEMP;
RENAME TABLE INSURED_BY_STATE TO INSURED_BY_STATE_TEMP;
--Join Abbreviations to the INSURED_BY_STATE table
USE WEIGAND_PORTFOLIO;
CREATE TABLE IF NOT EXISTS INSURED_BY_STATE AS (
    SELECT T1.STATE,
        T2.STATE_ABBR,
        T2.TYPE,
        T1.CIVI_NONINST_POP,
        T1.MALE,
        T1.FEMALE,
        T1.NATIVE_BORN,
        T1.NATURALIZED,
        T1.NOT_A_CITIZEN,
        T1.WITH_A_DISABILITY,
        T1.NO_DISABILITY,
        T1.HH_INCOME_UNDER_25K,
        T1.HH_INCOME_25_50K,
        T1.HH_INCOME_50_75K,
        T1.HH_INCOME_75_100K,
        T1.HH_INCOME_OVER_100K
    FROM INSURED_BY_STATE_TEMP T1
        LEFT JOIN STATE_ABBREVIATIONS T2 ON T1.STATE = T2.STATE
);
-- DROP TEMP TABLE
DROP TABLE IF EXISTS INSURED_BY_STATE_TEMP;
ALTER TABLE INSURED_BY_STATE
ADD KEY (STATE_ABBR);
DESCRIBE INSURED_BY_STATE;
SELECT *
FROM INSURED_BY_STATE;
-------------------
-------------------
-- CREATE TABLE - UNINSURED BY STATE
USE WEIGAND_PORTFOLIO;
DROP TABLE IF EXISTS UNINSURED_BY_STATE;
CREATE TABLE IF NOT EXISTS UNINSURED_BY_STATE (
    STATE VARCHAR(50) NOT NULL,
    CIVI_NONINST_POP BIGINT NOT NULL,
    MALE BIGINT NOT NULL,
    FEMALE BIGINT NOT NULL,
    NATIVE_BORN BIGINT NOT NULL,
    NATURALIZED BIGINT NOT NULL,
    NOT_A_CITIZEN BIGINT NOT NULL,
    WITH_A_DISABILITY BIGINT NOT NULL,
    NO_DISABILITY BIGINT NOT NULL,
    HH_INCOME_UNDER_25K BIGINT NOT NULL,
    HH_INCOME_25_50K BIGINT NOT NULL,
    HH_INCOME_50_75K BIGINT NOT NULL,
    HH_INCOME_75_100K BIGINT NOT NULL,
    HH_INCOME_OVER_100K BIGINT NOT NULL
);
-- "C:\ProgramData\MySQL\MySQL Server 9.3\Uploads\Unisured - Health Insurance by State (2023 Census).csv"
USE WEIGAND_PORTFOLIO;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.3/Uploads/Unisured - Health Insurance by State (2023 Census).csv' INTO TABLE UNINSURED_BY_STATE FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (
    STATE,
    CIVI_NONINST_POP,
    MALE,
    FEMALE,
    NATIVE_BORN,
    NATURALIZED,
    NOT_A_CITIZEN,
    WITH_A_DISABILITY,
    NO_DISABILITY,
    HH_INCOME_UNDER_25K,
    HH_INCOME_25_50K,
    HH_INCOME_50_75K,
    HH_INCOME_75_100K,
    HH_INCOME_OVER_100K
);
DESCRIBE UNINSURED_BY_STATE;
SELECT *
FROM UNINSURED_BY_STATE;
RENAME TABLE UNINSURED_BY_STATE TO UNINSURED_BY_STATE_TEMP;
--Join Abbreviations to the UNINSURED_BY_STATE table
USE WEIGAND_PORTFOLIO;
CREATE TABLE IF NOT EXISTS UNINSURED_BY_STATE AS (
    SELECT T1.STATE,
        T2.STATE_ABBR,
        T2.TYPE,
        T1.CIVI_NONINST_POP,
        T1.MALE,
        T1.FEMALE,
        T1.NATIVE_BORN,
        T1.NATURALIZED,
        T1.NOT_A_CITIZEN,
        T1.WITH_A_DISABILITY,
        T1.NO_DISABILITY,
        T1.HH_INCOME_UNDER_25K,
        T1.HH_INCOME_25_50K,
        T1.HH_INCOME_50_75K,
        T1.HH_INCOME_75_100K,
        T1.HH_INCOME_OVER_100K
    FROM UNINSURED_BY_STATE_TEMP T1
        LEFT JOIN STATE_ABBREVIATIONS T2 ON T1.STATE = T2.STATE
);
-- DROP TEMP TABLE
DROP TABLE IF EXISTS UNINSURED_BY_STATE_TEMP;
ALTER TABLE UNINSURED_BY_STATE
ADD KEY (STATE_ABBR);
DESCRIBE UNINSURED_BY_STATE;
SELECT *
FROM UNINSURED_BY_STATE;
--
-- 
-- TABLES IN THIS SCRIPT
SELECT *
FROM state_abbreviations;
SELECT *
FROM state_life_expectancy;
SELECT *
FROM state_expenditure;
SELECT *
FROM insured_by_state;
SELECT *
FROM uninsured_by_state;